packages:
  - "src/*"
  - "shared/*"
  - "shared"
allowBuilds:
  prisma: false
  '@prisma/client': false
  '@prisma/engines': false
  better-sqlite3: true
  core-js: false
  electron: false
  electron-winstaller: false
  es5-ext: false
